//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean Draw
        {
            get
            {
                return SteamVR_Actions.default_Draw;
            }
        }
        
        public virtual SteamVR_Action_Boolean BrushSelectToggle
        {
            get
            {
                return SteamVR_Actions.default_BrushSelectToggle;
            }
        }
        
        public virtual SteamVR_Action_Boolean DrawEraseToggle
        {
            get
            {
                return SteamVR_Actions.default_DrawEraseToggle;
            }
        }
        
        public virtual SteamVR_Action_Boolean SaveButton
        {
            get
            {
                return SteamVR_Actions.default_SaveButton;
            }
        }
        
        public virtual SteamVR_Action_Vector2 DirectionSelectPositionHelper
        {
            get
            {
                return SteamVR_Actions.default_DirectionSelectPositionHelper;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
