//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean Draw
        {
            get
            {
                return SteamVR_Actions.default_Draw;
            }
        }
        
        public virtual SteamVR_Action_Boolean ModeSelect
        {
            get
            {
                return SteamVR_Actions.default_ModeSelect;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ModePosition
        {
            get
            {
                return SteamVR_Actions.default_ModePosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.default_MenuButton;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
